# Generated by Django 4.2.4 on 2023-09-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_intro', '0002_student_fathers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
